spring:
  application:
    name: microservice-eureka-server
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server-peer1
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  client:
     registerWithEureka: false  #false:不作为一个客户端注册到注册中心
     fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
#     serviceUrl:
#      defaultZone: http://eureka-server-peer2:8762/eureka/,http://eureka-server-peer3:8763/eureka/  #使用集群时 启用

