logging:
    level:
        tk.mybatis: DEBUG
        com.ztth.user: DEBUG
spring:
    application:
        name: m-user
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: test
        url: jdbc:mysql://39.106.156.121:3306/ztthmsg?useUnicode=true&characterEncoding=UTF8
        username: root
        password: ztthpassword
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
    basepackage: com.ztth.user.mapper
    xmlLocation: classpath:mapper/**/*.xml

server:
    port: 8766

redis:
    database: 1
    host: 39.106.156.121
    password:
    port: 6379
    timeout: 3000
    pool:
          max-active: 20
          max-idle: 5
          max-wait: 3000
    cluster:
          nodes: 39.106.156.121:6379
          timeout: 3000
          maxAttempts: 5


security:
  basic:
    enabled: true
  user:
    name: ztth  # 用户名
    password: ztthpass   # 用户密码

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        lease-expiration-duration-in-seconds: 30
        lease-renewal-interval-in-seconds: 10
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
             defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka/
        healthcheck:
              enabled: true
                    # docker 部署开启
#            defaultZone: http://center:8761/eureka/




