spring:
    application:
        name: m-gate
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null

redis:
    database: 1
    host: 39.106.156.121
    password:
    port: 6379
    timeout: 3000
    pool:
          max-active: 20
          max-idle: 5
          max-wait: 3000
    cluster:
          nodes: 39.106.156.121:6379
          timeout: 3000
          maxAttempts: 5

server:
    port: 8765 #启动端口
#
zuul:
  routes:
      admin:
            path: /user/**
            serviceId: m-user

      msg:
            path: /msg/**
            serviceId: m-api

      auth:
            path: /auth/**
            serviceId: m-auth

ribbon:
  eureka:
  enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000

security:
  basic:
    enabled: true
  user:
    name: ztth  # 用户名
    password: ztthpass   # 用户密码

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        serviceUrl:
            defaultZone: http://${security.user.name}:${security.user.password}@localhost:8761/eureka/




